[build]
  base = "."
  command = "cd apps/web && yarn build"
  publish = "apps/web/dist"

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "yarn web:dev"
  targetPort = 5173
  port = 8888
  autoLaunch = false

[[redirects]]
  from = "/callback"
  to = "/.netlify/functions/github-token"
  status = 200

[[redirects]]
  from = "/*"
  to = "/apps/web/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
