[build]
  base = "."
  command = "cd apps/web && npm run build"
  publish = "apps/web/dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/callback"
  to = "/.netlify/functions/github-token"
  status = 200

[[redirects]]
  from "/*"
  to = "/apps/web/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
