[build]
  base = "."
  command = "npx nx build web"
  publish = "dist/apps/web"

[build.environment]
  NODE_VERSION = "22"

[dev]
  command = "yarn web:dev"
  targetPort = 5173
  port = 8888
  autoLaunch = false

[[redirects]]
  from = "/callback"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/.netlify/functions/github-token"
  to = "/.netlify/functions/github-token"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
