[build]
  base = "."
  command = "npx vite build --config apps/web/vite.config.mts"
  publish = "dist/apps/web"

[build.environment]
  NODE_VERSION = "22"
  NX_CLOUD = "false"

[dev]
  command = "yarn web:dev"
  targetPort = 5173
  port = 8888
  autoLaunch = false

[[redirects]]
  from = "/callback"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
